version: '3'

services:
  app:
    build: ./app/
    env_file:
    - ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - db

  web-proxy:
    build: ./web-proxy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - db

#  rabbitmq:
#    image: rabbitmq
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#    volumes:
#      - ./data/rabbitmq:/var/lib/rabbitmq
#    restart: on-failure

  db:
    container_name: db
    image: postgres:16-alpine
    volumes:
      - ./data/base:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=wine
    env_file:
      - .env
